import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV # CHANGED: Added for potential future tuning
from sklearn.experimental import enable_halving_search_cv # CHANGED: Required for Halving search
from sklearn.model_selection import HalvingGridSearchCV, HalvingRandomSearchCV # CHANGED

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeRegressor # Changed from LinearRegression
from typing import List, Optional, Any, Dict
import uuid # To generate unique keys for data/pipelines
from pydantic import BaseModel, Field # For LLM structured output
from dotenv import load_dotenv
from langchain_groq import ChatGroq
import os

# --- Global In-Memory Stores ---
# These global dictionaries hold the actual dataframes and pipeline objects.
_data_store: Dict[str, pd.DataFrame] = {}
_pipeline_store: Dict[str, Any] = {}
_X_train_store: Dict[str, pd.DataFrame] = {}
_X_test_store: Dict[str, pd.DataFrame] = {}
_y_train_store: Dict[str, pd.Series] = {}
_y_test_store: Dict[str, pd.Series] = {}

load_dotenv()
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")
# The LLM instance. Passed to tools that need it (e.g., preprocess_data)

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

# --- Helper Pydantic Models for LLM structured output (used by preprocess_data) ---
class TargetColumnInput(BaseModel):
    target_column: str = Field(
        ...,
        description="Name of the target column to predict. Provide only the column name from the given list of columns.",
    )

class FeatureEngineeringCode(BaseModel):
    """Pydantic model for structuring the Python code generated by the LLM."""
    code: str = Field(
        ...,
        description=(
            "A string containing a single Python function named 'create_features'. "
            "This function must accept a pandas DataFrame as its only argument "
            "and return the modified DataFrame."
        )
    )

class FeatureEngineeringPrompt(BaseModel):
    """Pydantic model for structuring the extracted feature engineering prompt."""
    prompt: Optional[str] = Field(
        default=None,
        description=(
            "The specific, concise instruction for creating features. "
            "If no feature engineering is requested, this should be null or an empty string."
        )
    )

# --- Helper Functions ---
def _engineer_features(user_prompt: str, X_train_key: str, X_test_key: str, llm_instance: Any) -> dict:
    """
    Internal helper to generate and apply feature engineering code.
    This function is NOT intended to be called directly by the agent.
    """
    print("\n--- Step 2.5: Performing Feature Engineering ---")

    X_train = _X_train_store[X_train_key]
    X_test = _X_test_store[X_test_key]

    code_generation_prompt = f"""You are an expert Python data scientist. Your task is to write a single, self-contained Python function named `create_features`.

    **Function Definition:**
    - The function must be named `create_features`.
    - It must accept a pandas DataFrame `df` as its only argument.
    - It must return the modified pandas DataFrame.

    **User's Request for New Features:**
    "{user_prompt}"

    **Available DataFrame Columns:**
    {X_train.columns.tolist()}

    **First 5 Rows of Data (for context):**
    {X_train.head().to_string()}

    ---
    ### **CRITICAL INSTRUCTIONS for Robust Code Generation:**
    1.  **Avoid Side Effects**: The first line of your function **MUST** be `df = df.copy()` to ensure the original DataFrame is not modified.
    2.  **Self-Contained Function**: Import any necessary libraries (like `numpy` or `pandas`) **inside** the function to make it portable.
    3.  **Handle Missing Columns**: Before using a column, check if it exists in `df.columns`. If a required column is missing, print a warning and gracefully skip the creation of that specific feature.
    4.  **Prevent Division by Zero**: When creating ratio features (e.g., `a / b`), you **MUST** add a small epsilon (e.g., `1e-6`) to the denominator to avoid generating infinite values.
    5.  **Safe Log Transforms**: When using `np.log()`, add 1 to the column first (`np.log(df['column'] + 1)`) to handle zeros correctly.
    6.  **Correct Data Types**: Explicitly convert columns to the correct type (e.g., using `pd.to_numeric` with `errors='coerce'`) before performing operations.
    7.  **Code Clarity**: Add a brief, one-line comment explaining the purpose of each new feature you create.
    8.  **Return Value**: The function must end by returning the modified DataFrame.
    """
    # Use the passed LLM instance
    code_generator = llm_instance.with_structured_output(FeatureEngineeringCode)
    generated_code = code_generator.invoke(code_generation_prompt).code
    print(f"Generated code:\n{generated_code}")

    local_namespace = {}
    exec(generated_code, globals(), local_namespace)
    feature_creation_func = local_namespace['create_features']

    X_train_new = feature_creation_func(X_train.copy())
    X_test_new = feature_creation_func(X_test.copy())

    newly_added_columns = list(set(X_train_new.columns) - set(X_train.columns))
    print(f"New columns created: {newly_added_columns}")

    new_X_train_key = f"X_train_{uuid.uuid4()}"
    new_X_test_key = f"X_test_{uuid.uuid4()}"
    _X_train_store[new_X_train_key] = X_train_new
    _X_test_store[new_X_test_key] = X_test_new

    # Clean up old data keys
    if X_train_key in _X_train_store:
        del _X_train_store[X_train_key]
    if X_test_key in _X_test_store:
        del _X_test_store[X_test_key]

    return {
        "X_train_key": new_X_train_key,
        "X_test_key": new_X_test_key,
        "numeric_cols": X_train_new.select_dtypes(include=np.number).columns.tolist(),
        "categorical_cols": X_train_new.select_dtypes(include=['object', 'category']).columns.tolist(),
        "newly_added_columns": newly_added_columns
    }

def drop_missing_rows(df: pd.DataFrame, pct: float = 0.3) -> pd.DataFrame:
    """Helper function to drop rows with more than 'pct' missing values."""
    max_missing_cols = int(df.shape[1] * pct)
    missing_per_row = df.isnull().sum(axis=1)
    df_cleaned = df[missing_per_row <= max_missing_cols].copy()
    return df_cleaned

# --- Core Tool Functions ---

def load_data(path: str) -> dict:
    """
    Tool to load a dataframe from a specified CSV file path.
    Stores the loaded DataFrame in _data_store and returns its key.
    """
    if not path:
        raise ValueError("No path provided for dataset.")
    try:
        df = pd.read_csv(path)
        data_key = f"df_{uuid.uuid4()}"
        _data_store[data_key] = df
        print(f"Successfully loaded DataFrame from {path} with shape: {df.shape}. Stored with key: {data_key}")
        return {"data_key": data_key, "path": path}
    except FileNotFoundError:
        raise ValueError(f"File not found: {path}")
    except Exception as e:
        raise ValueError(f"Error loading data from {path}: {e}")

def preprocess_data(data_key: str, target_col: str, ignore_cols: Optional[List[str]] = None, llm_for_extraction: Any = None) -> dict:
    """
    Tool to preprocess a dataframe: splits into train/test, identifies numeric/categorical columns.
    Retrieves DataFrame by key, stores split data, and returns keys and column lists.
    `llm_for_extraction` must be provided if target column extraction is needed.
    """
    if data_key not in _data_store:
        raise ValueError(f"DataFrame with key {data_key} not found in store for preprocessing.")
    if llm_for_extraction is None:
        raise ValueError("LLM model (llm_for_extraction) must be provided to preprocess_data for target column extraction.")

    df = _data_store[data_key]

    if ignore_cols is None:
        ignore_cols = []

    train_df_copy = df.drop(columns=ignore_cols, errors='ignore').copy()

    # Drop rows with excessive missing values
    initial_rows = train_df_copy.shape[0]
    train_df_copy = drop_missing_rows(train_df_copy)
    rows_dropped = initial_rows - train_df_copy.shape[0]
    if rows_dropped > 0:
        print(f"Dropped {rows_dropped} rows due to excessive missing values during preprocessing.")

    # Use LLM for robust target column extraction
    target_extractor = llm_for_extraction.with_structured_output(TargetColumnInput)
    extracted_target = target_extractor.invoke(
            f"Extract the exact target column name similar to '{target_col}' "
            f"from the available columns: {list(train_df_copy.columns)}. Provide only the column name."
        ).target_column

    if extracted_target not in train_df_copy.columns:
        raise ValueError(f"Target column '{extracted_target}' not found in the DataFrame after dropping ignored columns/missing rows. Available columns: {list(train_df_copy.columns)}")
    else:
        target_col = extracted_target # Use the exact extracted target_col

    # Separate features (X) and target (y)
    X = train_df_copy.drop(columns=[target_col], axis=1)
    y = train_df_copy[target_col]

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Store the split data and generate keys
    X_train_key = f"X_train_{uuid.uuid4()}"
    X_test_key = f"X_test_{uuid.uuid4()}"
    y_train_key = f"y_train_{uuid.uuid4()}"
    y_test_key = f"y_test_{uuid.uuid4()}"

    _X_train_store[X_train_key] = X_train
    _X_test_store[X_test_key] = X_test
    _y_train_store[y_train_key] = y_train
    _y_test_store[y_test_key] = y_test

    # Identify numeric and categorical columns
    numeric_cols = X_train.select_dtypes(include=np.number).columns.tolist()
    categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()

    print(f"Data preprocessed. X_train shape: {X_train.shape}, X_test shape: {X_test.shape}")
    print(f"Numeric columns: {numeric_cols[:5]}{'...' if len(numeric_cols) > 5 else ''}")
    print(f"Categorical columns: {categorical_cols[:5]}{'...' if len(categorical_cols) > 5 else ''}")

    return {
        "X_train_key": X_train_key,
        "X_test_key": X_test_key,
        "y_train_key": y_train_key,
        "y_test_key": y_test_key,
        "numeric_cols": numeric_cols,
        "categorical_cols": categorical_cols,
        "target_column": target_col # Return the exact target column name used
    }

def select_imputer(numeric_type: str = "simple", categorical_type: str = "constant",
                   numeric_strategy: str = "mean", categorical_strategy: str = "constant") -> dict:
    """
    Tool to select and configure numeric and categorical imputers.
    Returns: A dictionary with string representations of the imputer types and strategies.
    The actual imputer objects will be built during pipeline construction.
    """
    numeric_imputer_params = {"type": numeric_type, "strategy": numeric_strategy}
    categorical_imputer_params = {"type": categorical_type, "strategy": categorical_strategy}

    if numeric_type not in ["simple", "knn"]:
        raise ValueError(f"Unsupported numeric imputer type: {numeric_type}. Choose 'simple' or 'knn'.")
    if numeric_type == "simple" and numeric_strategy not in ["mean", "median", "most_frequent", "constant"]:
        raise ValueError(f"Unsupported numeric imputer strategy for 'simple': {numeric_strategy}. Choose 'mean', 'median', 'most_frequent', or 'constant'.")

    if categorical_type not in ["simple", "constant"]:
        raise ValueError(f"Unsupported categorical imputer type: {categorical_type}. Choose 'simple' or 'constant'.")
    if categorical_type == "simple" and categorical_strategy not in ["most_frequent", "constant"]:
            raise ValueError(f"Unsupported categorical imputer strategy for 'simple': {categorical_strategy}. Choose 'most_frequent' or 'constant'.")
    elif categorical_type == "constant" and categorical_strategy != "constant":
        print(f"Warning: When categorical_type is 'constant', categorical_strategy should also be 'constant'. Ignoring '{categorical_strategy}'.")
        categorical_imputer_params["strategy"] = "constant"

    print(f"Selected numeric imputer: {numeric_type} with strategy {numeric_strategy}")
    print(f"Selected categorical imputer: {categorical_type} with strategy {categorical_imputer_params['strategy']}")

    return {
        "numeric_imputer_params": numeric_imputer_params,
        "categorical_imputer_params": categorical_imputer_params,
        "numeric_imputer_type": numeric_type, # Return for AgentState
        "numeric_imputer_strategy": numeric_strategy, # Return for AgentState
        "categorical_imputer_type": categorical_type, # Return for AgentState
        "categorical_imputer_strategy": categorical_imputer_params['strategy'] # Return actual used strategy
    }

def select_scaler(numeric_scaler: str = "standard", categorical_encoder: str = "onehot") -> dict:
    """
    Tool to select and configure a numeric scaler and a categorical encoder.
    Returns: A dictionary with string representations of the scaler/encoder types.
    The actual objects will be built during pipeline construction.
    """
    numeric_scaler_params = {"type": numeric_scaler}
    categorical_encoder_params = {"type": categorical_encoder}

    if numeric_scaler not in ["standard", "minmax", "none"]: # Added "none" for decision trees
        raise ValueError(f"Unsupported numeric scaler: {numeric_scaler}. Choose 'standard', 'minmax', or 'none'.")
    if categorical_encoder not in ["onehot", "ordinal"]:
        raise ValueError(f"Unsupported categorical encoder: {categorical_encoder}. Choose 'onehot' or 'ordinal'.")

    print(f"Selected numeric scaler: {numeric_scaler}")
    print(f"Selected categorical encoder: {categorical_encoder}")

    return {
        "numeric_scaler_params": numeric_scaler_params,
        "categorical_encoder_params": categorical_encoder_params,
        "numeric_scaler_type": numeric_scaler, # For AgentState.numeric_scaler_type
        "categorical_encoder_type": categorical_encoder # For AgentState.categorical_encoder_type
    }

def build_pipeline(numeric_cols: List[str], categorical_cols: List[str],
                   numeric_imputer_params: Dict[str, Any], categorical_imputer_params: Dict[str, Any],
                   numeric_scaler_params: Dict[str, Any], categorical_encoder_params: Dict[str, Any],
                   model_params: Dict[str, Any]) -> dict:
    """
    Tool to build a scikit-learn preprocessing and model pipeline for a Decision Tree Regressor.
    Constructs objects from parameters, stores the pipeline in _pipeline_store, and returns its key.
    """
    # Instantiate imputers
    if numeric_imputer_params["type"] == "simple":
        numeric_imputer = SimpleImputer(strategy=numeric_imputer_params["strategy"])
    elif numeric_imputer_params["type"] == "knn":
        numeric_imputer = KNNImputer()
    else:
        raise ValueError(f"Unknown numeric imputer type: {numeric_imputer_params['type']}")

    if categorical_imputer_params["type"] == "simple":
        if categorical_imputer_params["strategy"] == "constant":
            categorical_imputer = SimpleImputer(strategy="constant", fill_value="missing")
        else: # 'most_frequent'
            categorical_imputer = SimpleImputer(strategy=categorical_imputer_params["strategy"])
    elif categorical_imputer_params["type"] == "constant":
        categorical_imputer = SimpleImputer(strategy="constant", fill_value="missing")
    else:
        raise ValueError(f"Unknown categorical imputer type: {categorical_imputer_params['type']}")

    # Instantiate scalers/encoders
    if numeric_scaler_params["type"] == "standard":
        numeric_scaler_obj = StandardScaler()
    elif numeric_scaler_params["type"] == "minmax":
        numeric_scaler_obj = MinMaxScaler()
    elif numeric_scaler_params["type"] == "none":
        numeric_scaler_obj = 'passthrough' # Do not scale for decision trees
    else:
        raise ValueError(f"Unknown numeric scaler type: {numeric_scaler_params['type']}")

    if categorical_encoder_params["type"] == "onehot":
        categorical_encoder_obj = OneHotEncoder(handle_unknown="ignore")
    elif categorical_encoder_params["type"] == "ordinal":
        categorical_encoder_obj = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    else:
        raise ValueError(f"Unknown categorical encoder type: {categorical_encoder_params['type']}")

    # Create numeric pipeline steps, handling the 'none' scaler case
    numeric_pipeline_steps = [("imputer", numeric_imputer)]
    if numeric_scaler_obj != 'passthrough':
        numeric_pipeline_steps.append(("scaler", numeric_scaler_obj))
    numeric_pipeline = Pipeline(numeric_pipeline_steps)

    categorical_pipeline = Pipeline([
        ("imputer", categorical_imputer),
        ("encoder", categorical_encoder_obj)
    ])

    preprocessor = ColumnTransformer(
        [
            ("num", numeric_pipeline, numeric_cols),
            ("cat", categorical_pipeline, categorical_cols)
        ],
        remainder='passthrough'
    )

    # Instantiate the Decision Tree Regressor with specified parameters
    decision_tree_model = DecisionTreeRegressor(**model_params)

    pipeline = Pipeline([
        ("preprocessing", preprocessor),
        ("model", decision_tree_model)
    ])

    pipeline_key = f"pipeline_{uuid.uuid4()}"
    _pipeline_store[pipeline_key] = pipeline

    print(f"Pipeline with DecisionTreeRegressor built and stored with key: {pipeline_key}")
    print(f"Model Parameters: {model_params}")
    return {"pipeline_key": pipeline_key}


def train_model(pipeline_key: str, X_train_key: str, y_train_key: str) -> dict:
    """
    Tool to train a scikit-learn pipeline.
    Retrieves pipeline and data by keys, fits the pipeline, and updates the stored pipeline.
    This replaces the 'tune_and_train_model' from linear regression, as tuning is not
    mandatory in this simplified Decision Tree workflow.
    """
    if pipeline_key not in _pipeline_store:
        raise ValueError(f"Pipeline with key {pipeline_key} not found in store.")
    if X_train_key not in _X_train_store:
        raise ValueError(f"X_train with key {X_train_key} not found in store.")
    if y_train_key not in _y_train_store:
        raise ValueError(f"y_train with key {y_train_key} not found in store.")

    pipeline = _pipeline_store[pipeline_key]
    X_train = _X_train_store[X_train_key]
    y_train = _y_train_store[y_train_key]

    print("Training model...")
    pipeline.fit(X_train, y_train)
    print("Model training complete.")

    _pipeline_store[pipeline_key] = pipeline
    return {"pipeline_key": pipeline_key}


def evaluate_model(pipeline_key: str, X_test_key: str, y_test_key: str) -> dict:
    """
    Tool to evaluate a trained model using common regression metrics.
    Retrieves pipeline and data by keys, performs evaluation, and returns metrics.
    """
    try:
        if pipeline_key not in _pipeline_store:
            raise ValueError(f"Pipeline with key {pipeline_key} not found in store.")
        if X_test_key not in _X_test_store:
            raise ValueError(f"X_test with key {X_test_key} not found in store.")
        if y_test_key not in _y_test_store:
            raise ValueError(f"y_test with key {y_test_key} not found in store.")

        pipeline = _pipeline_store[pipeline_key]
        X_test = _X_test_store[X_test_key]
        y_test = _y_test_store[y_test_key]

        print("Evaluating model...")
        y_pred = pipeline.predict(X_test)
        
        # No inverse transform (np.exp) needed for Decision Trees unless a prior log transform was explicitly applied
        # during feature engineering or target preparation.
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)
        r2 = r2_score(y_test, y_pred)

        print("\n--- Model Evaluation Results ---")
        print(f"Target Mean: {y_test.mean():.2f}")
        print(f"Target Std: {y_test.std():.2f}")
        print(f"Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Mean Squared Error (MSE): {mse:.2f}")
        print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
        # Added a check for division by zero for Relative RMSE
        print(f"Relative RMSE (%): {(rmse / y_test.mean() * 100) if y_test.mean() != 0 else float('inf'):.2f}%")
        print(f"R-squared (R²): {r2:.2f}")
        print("--------------------------------")

        return {"evaluation_metrics": {"mae": mae, "mse": mse, "rmse": rmse, "r2": r2}, "status": "completed successfully"}

    except Exception as e:
        print(f"Error during evaluation: {e}")
        return {"evaluation_metrics": {"mae": "NA", "mse": "NA", "rmse": "NA", "r2": "NA"}, "status": "failed", "error": str(e)}

def print_df_head(data_key: Optional[str] = None, X_train_key: Optional[str] = None,
                  X_test_key: Optional[str] = None, y_train_key: Optional[str] = None,
                  y_test_key: Optional[str] = None) -> dict:
    """
    Tool to print the head of a specified DataFrame (full, X_train, X_test, y_train, or y_test)
    from the global stores.
    Returns: A dictionary indicating if the head was printed and a sample.
    """
    df_to_print = None
    df_name = ""

    if data_key and data_key in _data_store:
        df_to_print = _data_store[data_key]
        df_name = "Full DataFrame"
    elif X_train_key and X_train_key in _X_train_store:
        df_to_print = _X_train_store[X_train_key]
        df_name = "X_train"
    elif X_test_key and X_test_key in _X_test_store:
        df_to_print = _X_test_store[X_test_key]
        df_name = "X_test"
    elif y_train_key and y_train_key in _y_train_store:
        df_to_print = _y_train_store[y_train_key].to_frame(name='target')
        df_name = "y_train"
    elif y_test_key and y_test_key in _y_test_store:
        df_to_print = _y_test_store[y_test_key].to_frame(name='target')
        df_name = "y_test"

    if df_to_print is not None:
        print(f"\n--- {df_name} Head ---")
        print(df_to_print.head().to_string())
        print("----------------------")
        return {"df_head_printed": True, "df_sample_head": df_to_print.head().to_dict('records'), "df_name": df_name}
    else:
        print("No specified DataFrame key found in the stores for printing head.")
        return {"df_head_printed": False}

# --- Orchestrator Tool: run_decision_tree_workflow ---

def run_decision_tree_workflow(
    path: str,
    target_column: str,
    user_query : str,
    ignore_columns: Optional[List[str]] = None,
    numeric_imputer_type: str = "simple",
    numeric_imputer_strategy: str = "mean",
    categorical_imputer_type: str = "simple",
    categorical_imputer_strategy: str = "constant",
    numeric_scaler_type: str = "none", # Default to 'none' for Decision Trees
    categorical_encoder_type: str = "onehot",
    # --- Decision Tree Regressor Hyperparameters ---
    criterion: str = "squared_error",
    max_depth: Optional[int] = None,
    min_samples_split: int = 2,
    min_samples_leaf: int = 1,
) -> dict:
    """
    A comprehensive tool to orchestrate an end-to-end Decision Tree Regressor workflow.
    """

    # Initialize all potential return values
    return_values = {
        "path": path, "target_column": target_column, "ignore_columns": ignore_columns,
        "feature_engineering_prompt": None,
        "numeric_imputer_type": numeric_imputer_type, "numeric_imputer_strategy": numeric_imputer_strategy,
        "categorical_imputer_type": categorical_imputer_type, "categorical_imputer_strategy": categorical_imputer_strategy,
        "numeric_scaler_type": numeric_scaler_type, "categorical_encoder_type": categorical_encoder_type,
        "model_hyperparameters": {"criterion": criterion, "max_depth": max_depth, "min_samples_split": min_samples_split, "min_samples_leaf": min_samples_leaf},
        "data_key": None, "X_train_key": None, "X_test_key": None, "y_train_key": None, "y_test_key": None,
        "numeric_cols": [], "categorical_cols": [], "newly_added_columns": [],
        "pipeline_key": None, "evaluation_metrics": {},
        "workflow_summary": {"status": "started", "steps_completed": [], "error": None}
    }

    print(f"Starting Decision Tree workflow for {path} with target '{target_column}'...")

    try:
        # Step 1: Load Data
        print("\n--- Step 1: Loading Data ---")
        load_result = load_data(path=path)
        return_values.update(load_result)
        return_values["workflow_summary"]["steps_completed"].append("Data Loaded")

        # Step 2: Preprocess Data
        print("\n--- Step 2: Preprocessing Data ---")
        preprocess_result = preprocess_data(
            data_key=return_values["data_key"], target_col=target_column,
            ignore_cols=ignore_columns, llm_for_extraction=llm
        )
        return_values.update(preprocess_result)
        return_values["workflow_summary"]["steps_completed"].append("Data Preprocessed")
        return_values["workflow_summary"]["numeric_columns"] = return_values["numeric_cols"]
        return_values["workflow_summary"]["categorical_columns"] = return_values["categorical_cols"]

        # Step 2.5: Checking for Feature Engineering Request
        print("\n--- Step 2.5: Checking for Feature Engineering Request ---")
        extractor = llm.with_structured_output(FeatureEngineeringPrompt)
        print("User Query:", user_query)
        extraction_prompt_text = (
            "From the following user query, extract the specific instruction for "
            "creating new features. If no such instruction exists, return null.\n\n"
            f"USER QUERY: '{user_query}'"
        )
        extracted_prompt = extractor.invoke(extraction_prompt_text).prompt
        print("Extracted prompt:", extracted_prompt)

        # Update state with the extracted prompt for logging purposes
        return_values["feature_engineering_prompt"] = extracted_prompt

        if extracted_prompt:
            print(f"Found feature engineering instruction: '{extracted_prompt}'")
            feature_eng_result = _engineer_features(
                user_prompt=extracted_prompt,
                X_train_key=return_values["X_train_key"],
                X_test_key=return_values["X_test_key"],
                llm_instance=llm
            )
            return_values.update(feature_eng_result)
            return_values["workflow_summary"]["steps_completed"].append("Feature Engineering")
            return_values["workflow_summary"]["newly_added_columns"] = return_values["newly_added_columns"]
        else:
            print("No feature engineering request found in the query.")
            pass
            
        # NOTE: Correlation drop step has been removed for Decision Trees.
        print("\n--- Skipping Correlation Drop (not typically necessary for Decision Trees) ---")

        # Step 4: Select Imputers
        print("\n--- Step 4: Selecting Imputers ---")
        imputer_result = select_imputer(
            numeric_type=numeric_imputer_type, categorical_type=categorical_imputer_type,
            numeric_strategy=numeric_imputer_strategy, categorical_strategy=categorical_imputer_strategy
        )
        return_values.update(imputer_result)
        return_values["workflow_summary"]["steps_completed"].append("Imputers Selected")

        # Step 5: Select Scaler and Encoder
        print("\n--- Step 5: Selecting Scaler and Encoder ---")
        scaler_encoder_result = select_scaler(
            numeric_scaler=numeric_scaler_type, categorical_encoder=categorical_encoder_type
        )
        return_values.update(scaler_encoder_result)
        return_values["workflow_summary"]["steps_completed"].append("Scaler and Encoder Selected")
        return_values["workflow_summary"]["numeric_scaler"] = return_values["numeric_scaler_type"]
        return_values["workflow_summary"]["categorical_encoder"] = return_values["categorical_encoder_type"]

        # Step 6: Build Pipeline
        print("\n--- Step 6: Building Pipeline ---")
        build_pipeline_result = build_pipeline(
            numeric_cols=return_values["numeric_cols"], categorical_cols=return_values["categorical_cols"],
            numeric_imputer_params=imputer_result["numeric_imputer_params"],
            categorical_imputer_params=imputer_result["categorical_imputer_params"],
            numeric_scaler_params=scaler_encoder_result["numeric_scaler_params"],
            categorical_encoder_params=scaler_encoder_result["categorical_encoder_params"],
            model_params=return_values["model_hyperparameters"]
        )
        return_values.update(build_pipeline_result)
        return_values["workflow_summary"]["steps_completed"].append("Pipeline Built")

        # Step 7: Train Model (simplified from tune_and_train_model)
        print("\n--- Step 7: Training Model ---")
        train_model_result = train_model(
            pipeline_key=return_values["pipeline_key"],
            X_train_key=return_values["X_train_key"], y_train_key=return_values["y_train_key"]
        )
        return_values.update(train_model_result)
        return_values["workflow_summary"]["steps_completed"].append("Model Trained")

        # Step 8: Evaluate Model
        print("\n--- Step 8: Evaluating Model ---")
        evaluate_model_result = evaluate_model(
            pipeline_key=return_values["pipeline_key"],
            X_test_key=return_values["X_test_key"], y_test_key=return_values["y_test_key"]
        )
        return_values["workflow_summary"]["steps_completed"].append("Model Evaluated")
        return_values["evaluation_metrics"] = evaluate_model_result["evaluation_metrics"]
        if evaluate_model_result["status"] == "failed":
            raise Exception(f"Model evaluation failed: {evaluate_model_result.get('error', 'Unknown error')}")

        return_values["workflow_summary"]["status"] = "completed successfully"
        print(f"\nML Workflow {return_values['workflow_summary']['status']}!")

    except Exception as e:
        return_values["workflow_summary"]["status"] = "failed"
        return_values["workflow_summary"]["error"] = str(e)
        print(f"\nML Workflow {return_values['workflow_summary']['status']} with error: {e}")

    return return_values